---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Europe/London
  METALLB_LB_RANGE: 10.0.0.200-10.0.0.250
  METALLB_K8S_GATEWAY_ADDR: 10.0.0.240
  METALLB_INGRESS_ADDR: 10.0.0.241
