# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:j1mFiIOnn2hJ0d/OtVOk5Q==,iv:b3pUPdpz2a/Bm8YZOTNTi1rW3P9GgzEfQygLTj1BchQ=,tag:tiU0SCya5zWo34em0qdYXg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:C4Crc4ycjEUzP85Cnm6fsyCGaik6,iv:oAPDsy/32S+x9oiunNjRZJVj3daVAnFEej9yfzwLZDw=,tag:BgPzC7IOf2b7go77XtYSjw==,type:str]
    SECRET_PROVIDERS_GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:6YaNvIVM/Zq7UitgtjTIb1RIZmuwZ7S8w9cblNCRmEFKihAewTUQlJK0V+lNG/V/cQ+FJ6NKfSOtMHUevO1gctRCsyi0XBF2,iv:pBg1jbTdLoeZEb/XwF1pqe3OmAvdiNcY1Bbzsuy+wS8=,tag:B206Fc20Hcwi/pWGwtfDVw==,type:str]
    SECRET_PROVIDERS_GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:0xFBhZO/PFA95ZayVa9V8YxJkSdGS7TcAp37ATaY0GdPEEc=,iv:pBEEv44aLOrB4NUsosNYXvRbyFdBMa6wFDuv/kGskyc=,tag:J+O2rBjsmS4WJgTlmy5JVA==,type:str]
    SECRET_OAUTH_SECRET: ENC[AES256_GCM,data:7VZAqr2+eBFjle8WWx4pGk9kN95ct9ujPP7hltbpSYI1L4QS4AI/XGr5elk=,iv:r2NaA8+na17sXDUp0qLYFb/72LK3NJjNxtJ4ziDsz7s=,tag:ewiiWsrcHTfTwPqpRiwhww==,type:str]
    SECRET_WHITELIST: ENC[AES256_GCM,data:HkPcK0G8ifQ4RI3gMpLpZQNtJgNF,iv:u8KYVP38K7DR5vsFlXQc1jxxsLwh58aTtTNEoQgCeUc=,tag:D5UydGRbT3Wrsj91pvbMjg==,type:str]
    SECRET_FLUX_DISCORD_ADDRESS: ENC[AES256_GCM,data:vFiKEV1safwZxkfDwku3rUITcdJ61tW6TPTA0AwGfywoxy+sUtxgDC+zdV850lBJ7CBMam38/pw8udoAiXgjnHxXJv/g5hl1o9jCSPkh2JQD1FfsicHLcdV9QIT8wNGB3GGbZQt8kYn1nAyy5RGJe6jyFZ3KWCGq,iv:xVybENy3/EC4mj9i+lOzEMgTrbpXwHnu5d9Z987XmX4=,tag:X8+MAW3t46OQ9vMsUmBSlA==,type:str]
    SECRET_FLUX_GITHUB_TOKEN: ENC[AES256_GCM,data:CipKIDT2GNBLyW30JvcswD0Sv6twd09hYcnIKqVcsgOoE+GPEUWw/Q==,iv:G61Gtj1RWRMp5l75BSTuo/5p0/xRKzikhrj/DWokpjg=,tag:MVKQGnf4p0cq4aXXCuJswA==,type:str]
    SECRET_PLEX_CLAIM_TOKEN: ENC[AES256_GCM,data:QaseJrhyy/381irsS6wEBUcnaYWfbIbfKUQ=,iv:x4gE9qmqxlIxdSZcgOWXWgiW/n6vwRrCx6XdZn3p5Po=,tag:ZCA/77tmcKOV+LLrp6gUuA==,type:str]
    SECRET_SMTP_USERNAME: ENC[AES256_GCM,data:BduJfdiF3iGx3O22/n/bnVMWmJns,iv:P2RlRIy7MOX8SyYvlK8yyeF7ZkN2GvAjKDypyGBizzQ=,tag:4TKQ5cMZ0/5CU3jCcPSdqA==,type:str]
    SECRET_SMTP_PASSWORD: ENC[AES256_GCM,data:32H6KygoPa2Z57d07TvkhQ==,iv:9PmKgKUxqqSVNB4IPC//z6lFx8RfqbxlMc3JCPZym5A=,tag:aqJVstDqHaLd7+p8uCBKLg==,type:str]
    SECRET_SMTP_SERVER: ENC[AES256_GCM,data:CHAvj8/kVwV32od4otQ=,iv:M7Zu2pr81HWT2q6Hb6ZFErgcapnuwFlNfHIOiGQWnYg=,tag:SuPA41p6xWDao23UwuiPbg==,type:str]
    SECRET_LDAP_BASE_DN: ENC[AES256_GCM,data:4RPHeEBHKmkvGA0E+ET0H5xmoA/0Ng==,iv:XN+lZHXQqHPEcS65t9SG9vPcBptlcAdiUkssvqRUs9k=,tag:AbSr2yUsH73a62G9wbLhPA==,type:str]
    SECRET_LDAP_ADMIN_USERNAME: ENC[AES256_GCM,data:tkYCNWs=,iv:HRoQ+gaaoHG5mIoUB+Xw7Tb8wp203B6MyGsIvW7mHTg=,tag:KX56dTe1xbUP/2ZgPN2bWg==,type:str]
    SECRET_LDAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:njrJkvFt7nrQ2CoAJRAnokUWlIMzBHh/GZ1mt6zBEwJ2r3Xk,iv:Rk47qsgAmq/t+YfH5u85NpjU2Y+30M+ePVDjQmppLaM=,tag:mxhJa1Wm7PmzWgRoP6X+og==,type:str]
    SECRET_CODE_SERVER_PW: ENC[AES256_GCM,data:XXCRxTs2kQbuo9t/qoVGAiOp+zjshNy0,iv:F3AF/uDW3O9LcVYzH6a+lbMu9EcND23hmtv6ZscXe8U=,tag:3V5mGtv4XkFF2hHTTwtD9A==,type:str]
    SECRET_MINIO_ROOT_USER: ENC[AES256_GCM,data:397jQ4zX+qXc5tI=,iv:1svjBjnl8wKBpRibk8q2/AW9OXE3qUcoBojxYlJIc+w=,tag:9olng1AIj85NkvOEWauwIA==,type:str]
    SECRET_MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:3xnKHuITV+Vh/zzSZQjtzvo4PLqjTEKN,iv:lKJkHXarMhkMeAQE/NtLLvK5RNHlaz6xRbFmke8luF0=,tag:stI+e3lzJLOfR3EltkpOEg==,type:str]
    SECRET_MINIO_USER: ENC[AES256_GCM,data:XHZwS9Y2/coi9g==,iv:uA5UVgFygh8E3oc+6JWrwCpS/t/m5mr81vDi0E9ZUJk=,tag:k88PTh3ajs84bX3y2Jozlw==,type:str]
    SECRET_MINIO_SECRET_KEY: ENC[AES256_GCM,data:yLfniZLp/gdh/CgSM7pIpAJAty2ZLDukyP1psu/9sKUL7XmdRMh6CI5+irkFdHuC,iv:Qgl6MSh7lJ7hNBybA86XjSZk0Kjb/GZs5JdJER4xhoU=,tag:iFnxnu5f2jQZGo1VmmA6PA==,type:str]
    SECRET_POSTGRESSQL_USER: ENC[AES256_GCM,data:S0IUigB8sZEdiA==,iv:S89/3s0sbsSlYUp4mMwtbpoajUkr1gkaFpE1FZEz7NE=,tag:MkogQzQawhv1jMMM/UZBwQ==,type:str]
    SECRET_POSTGRESSQL_PASSWORD: ENC[AES256_GCM,data:B4tHON/q1yeiKqNytZr8Iee4dds=,iv:/Eh2lj5+PElJ2pyldFdh/6BEKkUX+L68bGuBOapNWK8=,tag:Fay1RIYhxxiLlROmV2WIUQ==,type:str]
    SECRET_REDIS_PASSWORD: ENC[AES256_GCM,data:w8nytLi398ocuUBFSBBx1OMWEEHav8rlWR+FohERykBmCOiq,iv:MJKmcvzDRukCVVZjT4V4FcotDQUxZIRqrlZY3h4zV2w=,tag:raRb8u0Y0C0D6TNTttdt+w==,type:str]
    SECRET_EMQX_ADMIN_PASSWORD: ENC[AES256_GCM,data:cq1f7be28KbBfACLN+Wi7w==,iv:80qVeIOPsdxlvzIAR3gB2t3GyCFEenHJTo2YMrT1Ooc=,tag:e6R8Rl0VejFxVVb/eR0r3Q==,type:str]
    SECRET_EMQX_USER1_NAME: ENC[AES256_GCM,data:q1yyHiwXxCKZkA==,iv:60dnti8NAqVz/uAM49oKDoijkBjsW6rWKQskRo2EQkM=,tag:NS5rneKh6at2oHDtAH7Juw==,type:str]
    SECRET_EMQX_USER1_PASSWORD: ENC[AES256_GCM,data:R15HYo+OP7fD8BaPTWldmQ==,iv:xpoAJg5xcOCPJZOWznmaZf4wT4CvwI5A34kPC5oZZq4=,tag:EuAnny5BmEqdYhPR9/9kpw==,type:str]
    SECRET_HASS_POSTGRES_URL: ENC[AES256_GCM,data:n92xDy1HRGP/VMFcufLMhqf6uqv/+J3W5wcF2MOSbDL3+Fh40A==,iv:3Vpu5ZgvVvCj9tsRAyjc6uhRZbimo0pY7gTzAO3YJkE=,tag:XIjhPOWzcyvs2YAkY5GDKg==,type:str]
    #ENC[AES256_GCM,data:snDDc0vn37wliKQdmpmek5Ula4wcnF+kCRQzw+Wy/O3Q4A==,iv:UrSfLYkVM2Bfd2QXEYHE2qQqC5XgS1Mn3NyI6va5yaI=,tag:KdWawy02DOi9JOoCNnZbgw==,type:comment]
    #ENC[AES256_GCM,data:FdfsYF+c9LIvP3pKQTDTZfaWdrHfm/VKDU5hjTB5Dd9Y0A==,iv:S6fLT6Em+lF1GNQqVyEvf1WaBA8//qb4oxPOMBe/NE8=,tag:Swp1wk04zlpf71EOnf49VA==,type:comment]
    SECRET_HASS_PIRATEWEATHER_API_KEY: ENC[AES256_GCM,data:TJJB82SBfuv2+LXDEk/xgOs3fJKmWO6WoFfNn6uvXvYB1iP8DIrLsQ==,iv:tL9YmwV3EuR1CaUQ7Hp64CQaOA5OvuEZ4SDVUzSre2E=,tag:0/bHSxMx6v8+wUxVMLiqAQ==,type:str]
    SECRET_OVPN_USER: ENC[AES256_GCM,data:soY/ArH/prI0lnodeF+pVtNeKmIFLWYF,iv:AI5JKlm03/tjLKyfUuucKjkWYNmt670YRrqhnzXwwq8=,tag:6W2+9NZrSX03+nRu7jtzqA==,type:str]
    SECRET_OVPN_PASS: ENC[AES256_GCM,data:bNEKlAvcBWtroL7rLmAHGPAKND68wjcq,iv:UjBfJ6gotPqpjGJjdlzoBDFFWMzK7pLjyjwk11k8VB4=,tag:trEqrWKu1LKDdNNRe/f2qQ==,type:str]
    SECRET_ALERT_MANAGER_DISCORD_WEBHOOK: ENC[AES256_GCM,data:9Dbu96V0OuSORRE67JL/k2NV8oZeK2dP1H3YJ1a6MfRWZLDej9A5NC1Ak4L3Nbe0ElVaQfGfCwNdS4nOWUgxilAr7A4UG5eaByaV0me/igKuqHl6gGdk4Rn/cCAQqnpZRgVEwc14ukUQQaOiEW8xqkLUtpnj3LDG5lzxqA==,iv:hSTKbRD4ifqD3g7EDmdLbDKl2VSPgy4D/ZQef2MYyHQ=,tag:wflTshSxDTb85lTPlhNODg==,type:str]
    SECRET_ALERT_MANAGER_SLACK_WEBHOOK: ENC[AES256_GCM,data:ElrDuROzJ4/tmgCZruYg9WpDFotXzh97LBjUtJ9ZazWA93JaiHaAH4Ia4LHAzmoAGaK0UuCca+f+xV/GDe/FBx1Bd1Xt6+ryTsb1n0y/qw==,iv:WSARCFe5WXOSCfjEfbCoykabm50H+HeJel5j9owZXwo=,tag:nVcsKpRseLyXkKDulq3RCA==,type:str]
    SECRET_GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:pahZdkCp/1NDAP5rGrrZfc184cv4Q1vL96H2w2o/KbLG9ipB,iv:x43NYJNSasp8UiUvHWaS0DoSRinqe/mhfELr6v6bh7M=,tag:7bZCTUR0AkHnL1DJtRK6qw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l2ynvs6f5sug5hf5yzd3dedd4yusth2rwxg77xxllg8kgcdd2f8sw965ed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRDZjQ213TkpodU53Tmkx
            VVdzdXlIVVdmQnMwQVl2OXpJNGNSWnBVeXpVCldVSlcxemMzRW0rMzd6WVdnMXla
            Mzc1NHpIdkdldG1uTVdURk5xZFZsZmsKLS0tIG9BR1hnRW1tTTZzaUpvaGRSbEhE
            WnBPVkJadmhOMUdEWEV0NEQ5ZUQ0d0UKZrNratGhHegq6iAMqJRHnS+w+Nt0Yl/+
            mnadWTsJ9E3tdIDSlj5GQ91zEYDbVlW17OqbOcBJp2CFy6vhIY1jag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-10T16:56:01Z"
    mac: ENC[AES256_GCM,data:RZGvgUBLKVfF45m1qvtqB6DsdJIS9BdWB6ad0hdSC0rRxJfAnszQ9j2CK+nQalUSUzxYxpp3SG0PfF8F6fJnh5aV0umkT/cvHQAEq2P7A+4Uj5eunpVcszn9E3K8LzFBCLbmVt4t7ydWjVLg73nHdwZkubjGYHkQTboFz1lkfv4=,iv:uqohXaJhwoBc9t2E4ZnHpScCyCeJU+IR5cvupfP0rmM=,tag:VLuBuOlra7EAiXIMpTT+Tw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
