---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-config
  namespace: monitoring
  labels:
    kasten-io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hdd-nfs-storage
  resources:
    requests:
      storage: 1Gi
